[build]
  command = "npm run build"
  publish = ".next"

# Fix CSP headers for Next.js compatibility
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googleapis.com *.gstatic.com *.cloudflare.com *.stripe.com; style-src 'self' 'unsafe-inline' *.googleapis.com *.gstatic.com; img-src 'self' data: blob: *.googleapis.com *.gstatic.com *.supabase.co *.cloudflare.com *.stripe.com; font-src 'self' *.googleapis.com *.gstatic.com; connect-src 'self' *.supabase.co *.stripe.com *.n8n.io; frame-src 'self' *.stripe.com; object-src 'none'; base-uri 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"

[[plugins]]
  package = "@netlify/plugin-nextjs"
