'use client';

import { motion } from 'framer-motion';

const videoScripts = [
  {
    id: 1,
    title: '5 Tips for Branding Success',
    publishDate: '2024-03-20',
    previewLink: 'https://example.com/video-preview-1'
  },
  {
    id: 2,
    title: 'Mastering Social Media Marketing',
    publishDate: '2024-03-25',
    previewLink: 'https://example.com/video-preview-2'
  },
  {
    id: 3,
    title: 'The Future of AI in Business',
    publishDate: '2024-04-01',
    previewLink: 'https://example.com/video-preview-3'
  },
  {
    id: 4,
    title: 'Building Your Online Presence',
    publishDate: '2024-04-05',
    previewLink: 'https://example.com/video-preview-4'
  }
];

export default function VideoContentQueue() {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-6">Video Content Queue</h2>
      <div className="space-y-4 mb-8">
        {videoScripts.map((video, index) => (
          <motion.div
            key={video.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="bg-deep-navy/80 p-4 rounded-xl border border-electric-blue/20"
          >
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-lg font-semibold">{video.title}</h3>
              <span className="bg-electric-blue/10 text-electric-blue px-2 py-1 rounded-full text-sm">
                Generated by VideoContent AI
              </span>
            </div>
            <div className="flex items-center justify-between">
              <p className="text-soft-gray/80">
                Scheduled: {new Date(video.publishDate).toLocaleDateString()}
              </p>
              <a
                href={video.previewLink}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-secondary"
              >
                Preview
              </a>
            </div>
          </motion.div>
        ))}
      </div>
      <button
        className="btn-primary w-full"
        onClick={() => toast('Feature coming soon!')}
      >
        Request Custom Video Script
      </button>
    </div>
  );
} 