-- SKRBL AI Agent Workflow Logging Tables
-- Generated by QUAD UP 401 migration

-- ============================================================================
-- agent_workflow_executions
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.agent_workflow_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  execution_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_name TEXT,
  superhero_name TEXT,
  n8n_workflow_id TEXT,
  user_id UUID,
  user_role TEXT,
  session_id TEXT,
  user_prompt TEXT,
  workflow_capabilities JSONB,
  estimated_duration INT,
  status TEXT,
  success BOOLEAN,
  error_message TEXT,
  previous_agent TEXT,
  handoff_reason TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS agent_workflow_executions_execution_id_idx ON public.agent_workflow_executions (execution_id);
CREATE INDEX IF NOT EXISTS agent_workflow_executions_agent_id_idx ON public.agent_workflow_executions (agent_id);

ALTER TABLE public.agent_workflow_executions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "internal_access_agent_workflow_executions" ON public.agent_workflow_executions
  FOR SELECT USING (true);
CREATE POLICY "insert_agent_workflow_executions" ON public.agent_workflow_executions
  FOR INSERT WITH CHECK (true);

-- ============================================================================
-- agent_workflow_requests
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.agent_workflow_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id TEXT NOT NULL,
  agent_name TEXT,
  superhero_name TEXT,
  user_id UUID,
  user_role TEXT,
  session_id TEXT,
  user_prompt TEXT,
  has_workflow BOOLEAN,
  requires_premium BOOLEAN,
  workflow_capabilities JSONB,
  request_metadata JSONB,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.agent_workflow_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "internal_access_agent_workflow_requests" ON public.agent_workflow_requests
  FOR SELECT USING (true);
CREATE POLICY "insert_agent_workflow_requests" ON public.agent_workflow_requests
  FOR INSERT WITH CHECK (true);

-- ============================================================================
-- agent_workflow_errors
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.agent_workflow_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id TEXT,
  error_message TEXT,
  error_stack TEXT,
  request_url TEXT,
  request_method TEXT,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.agent_workflow_errors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "internal_access_agent_workflow_errors" ON public.agent_workflow_errors
  FOR SELECT USING (true);
CREATE POLICY "insert_agent_workflow_errors" ON public.agent_workflow_errors
  FOR INSERT WITH CHECK (true); 