name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  SKIP_ENV_VALIDATION: "true"

jobs:
  lint-build-test-18:
    name: CI / lint-build-test (18.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run build

  lint-build-test-20:
    name: CI / lint-build-test (20.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run build

      # NEW: upload the Next.js build so smoke-tests can consume it
      - name: Upload build artifact
        if: ${{ success() && hashFiles('.next/BUILD_ID') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
          retention-days: 1

  security-scan:
    name: CI / security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Soft audit: log advisories but do not fail PRs
      - name: Run security audit (soft)
        run: |
          set -e
          echo "Running npm audit (will not fail the job)…"
          npm audit --audit-level=moderate || true

  smoke-tests:
    name: CI / smoke-tests
    runs-on: ubuntu-latest
    needs: [lint-build-test-20]   # depends on the job that uploads the artifact
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        id: dl
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: build-files
          path: .next/

      # Fallback: if artifact not found (first run, re-run, etc.), build locally
      - name: Fallback build if artifact missing
        run: |
          if [ ! -f .next/BUILD_ID ]; then
            echo "Artifact missing — running a local build for smoke tests"
            npm ci
            npm run build
          else
            echo "Artifact present"
          fi

      - name: List downloaded files (debug)
        run: ls -la .next || true

      - name: Verify Next build output exists
        run: test -f .next/BUILD_ID

      - name: Check critical pages exist (compiled)
        run: |
          (ls -R .next | grep -qi "sports") || (echo "sports page not compiled"; exit 1)