name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  SKIP_ENV_VALIDATION: "true"

jobs:
  build-20:
    name: CI / lint-build-test (20.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint -- --fix || true
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: success() && hashFiles('.next/BUILD_ID') != ''
        with:
          name: build-files
          path: .next/
          retention-days: 1

  build-18:
    name: CI / lint-build-test (18.x)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint -- --fix || true
      - run: npm run build

  security-scan:
    name: CI / security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Soft fail: report but don't block merges
      - name: Run security audit (soft)
        run: |
          set -e
          echo "Running npm audit (soft)…"
          npm audit --audit-level=moderate || echo "npm audit had findings (soft)"

  smoke-tests:
    name: CI / smoke-tests
    runs-on: ubuntu-latest
    needs: [build-20]
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next/
        continue-on-error: true

      - name: List downloaded files (debug)
        run: ls -la .next || echo "No .next directory found"

      # If artifact missing, do a tiny local build as fallback
      - name: Setup Node for fallback build
        if: ${{ !hashFiles('.next/BUILD_ID') }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Install dependencies for fallback
        if: ${{ !hashFiles('.next/BUILD_ID') }}
        run: npm ci
        
      - name: Build for fallback
        if: ${{ !hashFiles('.next/BUILD_ID') }}
        run: npm run build

      - name: Verify Next build output exists
        run: |
          if [ ! -f .next/BUILD_ID ]; then
            echo "Missing .next/BUILD_ID - build artifacts not available"
            exit 1
          fi
          echo "Build ID found: $(cat .next/BUILD_ID)"

      - name: Check critical pages exist (compiled)
        run: |
          echo "Checking compiled pages..."
          if ! ls -R .next | grep -qi "sports"; then
            echo "Warning: sports page not found in compiled output"
            # Don't fail the build for missing pages - this is just a smoke test
          fi
          echo "Smoke test completed ✅"
