name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  SKIP_ENV_VALIDATION: "true"

jobs:
  lint-build-test-18:
    name: CI / lint-build-test (18.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  lint-build-test-20:
    name: CI / lint-build-test (20.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      # ✅ Always upload on Node 20 so smoke job can download it
      - name: Upload build artifact
        if: success() && startsWith(github.ref, 'refs/')
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
          retention-days: 1

  security-scan:
    name: CI / security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run security audit (soft)
        run: |
          set -e
          echo "Running npm audit (will not fail CI)..."
          npm audit --audit-level=moderate || true

  smoke-tests:
    name: CI / smoke-tests
    runs-on: ubuntu-latest
    needs: [lint-build-test-20]
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        id: dl
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next/

      - name: List downloaded files (debug)
        run: ls -la .next || true

      - name: Verify Next build output exists
        run: test -f .next/BUILD_ID || (echo "Missing .next/BUILD_ID"; exit 1)

      - name: Check critical pages exist (compiled)
        run: |
          (ls -R .next | grep -qi "sports") || (echo "sports page not compiled"; exit 1)
          echo "Artifacts look sane ✅"
