name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

permissions:
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  SKIP_ENV_VALIDATION: "true"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-20:
    name: CI / lint-build-test (20.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint -- --fix || true
      - run: npm run build
      - name: Upload build artifact
        if: success() && hashFiles('.next/BUILD_ID') != ''
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
          retention-days: 1

  build-18:
    name: CI / lint-build-test (18.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint -- --fix || true
      - run: npm run build

  security-scan:
    name: CI / security-scan (soft)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run npm audit (soft)
        run: npm audit --audit-level=moderate || echo "audit findings (soft); continuing"

  smoke-tests:
    name: CI / smoke-tests
    runs-on: ubuntu-latest
    needs: [build-20]
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts (if present)
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next/
        continue-on-error: true

      - name: List downloaded files (debug)
        run: ls -la .next || echo "No .next directory found"

      # Fallback local build if artifact missing
      - uses: actions/setup-node@v4
        if: ${{ !hashFiles('.next/BUILD_ID') }}
        with:
          node-version: 20
          cache: npm
      - run: npm ci
        if: ${{ !hashFiles('.next/BUILD_ID') }}
      - run: npm run build
        if: ${{ !hashFiles('.next/BUILD_ID') }}

      - name: Verify Next build output exists
        run: |
          if [ ! -f .next/BUILD_ID ]; then
            echo "Missing .next/BUILD_ID - build artifacts not available"
            exit 1
          fi
          echo "BUILD_ID: $(cat .next/BUILD_ID)"

      - name: Check critical pages exist (compiled)
        run: |
          if ! ls -R .next | grep -qi "sports"; then
            echo "Warn: compiled output did not show 'sports' path"
          fi
          echo "Smoke test ✅"
