name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: "true"
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"

      # ✅ Make token available to all steps (no explicit login step needed)
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Project/Env IDs pulled from repo “Variables” (Settings → Secrets and variables → Variables)
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Actor:   $GITHUB_ACTOR"
          echo "Branch:  $GITHUB_REF"
          echo "SHA:     $GITHUB_SHA"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint -- --fix || true

      - name: Build (safe)
        run: npm run build

      - name: Deploy to Railway
        uses: railwayapp/action@v3
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          projectId: ${{ vars.RAILWAY_PROJECT_ID }}
          environmentId: ${{ vars.RAILWAY_ENVIRONMENT_ID }}
          serviceName: skrblai-live
          detach: true

      - name: Smoke checks (non-fatal)
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD /        ->" && curl -Isf "$BASE_URL/"        | head -n 1 || true
          echo "HEAD /sports  ->" && curl -Isf "$BASE_URL/sports"  | head -n 1 || true
          echo "GET  /api/health ->" && curl -s "$BASE_URL/api/health" | head -n 1 || true
