name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: .
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for optional local build)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI (pinned)
        run: |
          curl -fsSL https://railway.app/install.sh | bash
          railway version || true

      - name: Verify Railway auth
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway whoami

      - name: Link project/env/service (explicit)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link \
            --project "${{ secrets.RAILWAY_PROJECT_ID }}" \
            --environment "${{ secrets.RAILWAY_ENV }}" \
            --service "${{ secrets.RAILWAY_SERVICE }}"

      # Optional build; remove if Railway builds from Dockerfile only
      - name: Build (optional, safe)
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi

      - name: Deploy (stream logs, fail on errors)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --verbose