name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: "true"
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print GitHub context (debug)
        run: |
          echo "Actor:   $GITHUB_ACTOR"
          echo "Branch:  $GITHUB_REF"
          echo "SHA:     $GITHUB_SHA"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint --fix || true

      - name: Build project
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Verify railway.json configuration
        run: |
          echo "Verifying railway.json exists and has correct configuration..."
          cat railway.json
          echo "Railway CLI version:"
          railway --version

      - name: Deploy via Railway CLI using railway.json
        run: railway up --service "skrblai-live" --detach --ci

      - name: Smoke checks (non-fatal)
        continue-on-error: true
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD /        ->" && curl -Isf "$BASE_URL/"        | head -n 1 || true
          echo "HEAD /sports  ->" && curl -Isf "$BASE_URL/sports"  | head -n 1 || true
          echo "GET  /api/health ->" && curl -s "$BASE_URL/api/health" | head -n 1 || true