name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Railway environment name"
        required: false
        default: "production"
      service:
        description: "Railway service name"
        required: false
        default: "skrbai-live"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Safe build flags to avoid static-gen crashes & OOMs
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: true
      # Provide harmless defaults for public vars so build won't die if someone imports them at build time
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Actor:   $GITHUB_ACTOR"
          echo "Branch:  $GITHUB_REF"
          echo "SHA:     $GITHUB_SHA"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint -- --fix || true

      - name: Build (safe)
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Print Railway context (debug)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway --version
          railway whoami || true
          railway status || true
          railway services --json || true

      # If you have ONE service connected to this repo, this is enough:
      - name: Deploy via Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --yes

      - name: Smoke checks (non-fatal)
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD /        ->" && curl -Isf "$BASE_URL/"        | head -n 1 || true
          echo "HEAD /sports  ->" && curl -Isf "$BASE_URL/sports"  | head -n 1 || true
          echo "GET  /api/health ->" && curl -s "$BASE_URL/api/health" | head -n 1 || true