name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Railway environment name"
        required: false
        default: "production"
      service:
        description: "Railway service name"
        required: false
        default: "skrbai-live"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Safe build flags to avoid static-gen crashes & OOMs
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: true
      # Provide harmless defaults for public vars so build won't die if someone imports them at build time
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Actor:   $GITHUB_ACTOR"
          echo "Branch:  $GITHUB_REF"
          echo "SHA:     $GITHUB_SHA"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint -- --fix || true

      - name: Build (safe)
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Verify Railway token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "::error::Missing RAILWAY_TOKEN secret. Add it in GitHub → Settings → Secrets → Actions."
            exit 1
          fi
          railway whoami || true
          railway status || true

      - name: Deploy via Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          SERVICE="${{ github.event.inputs.service || 'skrbai-live' }}"
          ENV_NAME="${{ github.event.inputs.environment || 'production' }}"
          echo "Deploying service=$SERVICE env=$ENV_NAME branch=master"
          railway deploy --service "$SERVICE" --environment "$ENV_NAME" --branch master --yes

      - name: Smoke checks (non-fatal)
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD /        ->" && curl -Isf "$BASE_URL/"        | head -n 1 || true
          echo "HEAD /sports  ->" && curl -Isf "$BASE_URL/sports"  | head -n 1 || true
          echo "GET  /api/health ->" && curl -s "$BASE_URL/api/health" | head -n 1 || true