name: Deploy to Railway (Dockerfile)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}
      RAILWAY_SERVICE_NAME: ${{ vars.RAILWAY_SERVICE_NAME }}
      SITE_BASE_URL: ${{ vars.SITE_BASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | bash

      - name: Preflight (Docker + config present)
        run: |
          echo "Service root: $(pwd)"
          test -f Dockerfile || (echo "Missing Dockerfile" && exit 1)
          test -f railway.json || (echo "Missing railway.json" && exit 1)

      - name: Verify token is present and valid
        run: |
          test -n "$RAILWAY_TOKEN" || (echo "RAILWAY_TOKEN missing" && exit 1)
          railway whoami || (echo "Invalid RAILWAY_TOKEN" && exit 1)

      - name: Link project/env/service (non-interactive)
        run: |
          railway link --project "$RAILWAY_PROJECT_ID" \
                       --environment "$RAILWAY_ENVIRONMENT_ID" \
                       --service "$RAILWAY_SERVICE_NAME"

      - name: Deploy (Dockerfile)
        run: railway up --yes --verbose

      - name: Post-deploy smoke (non-blocking)
        continue-on-error: true
        run: |
          BASE_URL="${SITE_BASE_URL:-https://skrblai.io}"
          echo "Smoke on ${BASE_URL}"
          curl -Isf "$BASE_URL/" | head -n1
          curl -s "$BASE_URL/api/health" || true