name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096
  SKIP_ENV_VALIDATION: "true"
  # harmless defaults so imports don't crash during build
  NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint -- --fix || true
      - run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # ✅ LOGIN FIRST (fixes “Unauthorized. Please login”)
      - name: Railway login (CI)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          test -n "$RAILWAY_TOKEN" || (echo "RAILWAY_TOKEN secret is missing"; exit 1)
          railway login --token="$RAILWAY_TOKEN"
          railway whoami

      - name: Link & select project/env
        env:
          RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}
        run: |
          test -n "$RAILWAY_PROJECT_ID" || (echo "RAILWAY_PROJECT_ID variable missing"; exit 1)
          test -n "$RAILWAY_ENVIRONMENT_ID" || (echo "RAILWAY_ENVIRONMENT_ID variable missing"; exit 1)
          railway link --project "$RAILWAY_PROJECT_ID"
          railway environment --environment "$RAILWAY_ENVIRONMENT_ID"
          railway status || true

      - name: Deploy via Railway CLI (non-interactive)
        run: railway up --ci

      - name: Smoke checks (non-fatal)
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD / ->" && curl -Isf "$BASE_URL/" | head -n 1 || true
          echo "HEAD /sports ->" && curl -Isf "$BASE_URL/sports" | head -n 1 || true
          echo "GET /api/health ->" && curl -s "$BASE_URL/api/health" | head -n 1 || true
