name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Railway environment name (optional; uses repo var by default)"
        required: false
        default: "production"
      service:
        description: "Railway service name (optional; not required)"
        required: false
        default: "skrbai-live"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: "true"
      # Safe defaults so build won’t crash if some public vars are referenced at build time
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Actor:   $GITHUB_ACTOR"
          echo "Branch:  $GITHUB_REF"
          echo "SHA:     $GITHUB_SHA"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint -- --fix || true

      - name: Build (safe)
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Railway login (CI)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token "$RAILWAY_TOKEN"


      - name: Railway link to project
        env:
          RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
        run: railway link --project "$RAILWAY_PROJECT_ID"

      - name: Select environment
        env:
          RAILWAY_ENV_ID: ${{ vars.RAILWAY_ENV_ID }}
        run: railway environment --environment "$RAILWAY_ENV_ID"

      - name: Deploy via Railway CLI

      - name: Link & select project/env
        env:
          RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}
        run: |
          railway link --project "$RAILWAY_PROJECT_ID"
          railway environment --environment "$RAILWAY_ENVIRONMENT_ID"

      - name: Deploy via Railway CLI (non-interactive)

        run: railway up --ci

      - name: Smoke checks (non-fatal)
        run: |
          BASE_URL="https://skrblai.io"
          echo "HEAD /            ->" && curl -Isf "$BASE_URL/"        | head -n 1 || true
          echo "HEAD /sports      ->" && curl -Isf "$BASE_URL/sports"  | head -n 1 || true
          echo "GET  /api/health  ->" && curl -s   "$BASE_URL/api/health" | head -n 1 || true
