name: Deploy to Railway

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: Railway environment name
        required: false
        default: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # 🔑 Put the token at the JOB level so EVERY railway step sees it
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
      RAILWAY_ENVIRONMENT_ID: ${{ vars.RAILWAY_ENVIRONMENT_ID }}

      # Safe build flags (prevents OOM & missing public env at build time)
      NODE_OPTIONS: --max-old-space-size=4096
      SKIP_ENV_VALIDATION: "true"
      NEXT_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "anon"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint -- --fix || true

      - name: Build
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # ✅ No explicit login command needed; RAILWAY_TOKEN in env is enough
      - name: Link & select project/env
        run: |
          railway link --project "$RAILWAY_PROJECT_ID"
          railway environment --environment "$RAILWAY_ENVIRONMENT_ID"

      - name: Deploy via Railway CLI (non-interactive)
        run: railway up --ci

      - name: Smoke checks (non-fatal)
        run: |
          set -e
          BASE_URL="https://skrblai.io"
          echo "HEAD /              ->" && curl -Isf "$BASE_URL/" | head -n 1 || true
          echo "HEAD /sports        ->" && curl -Isf "$BASE_URL/sports" | head -n 1 || true
          echo "GET  /api/health    ->" && curl -s    "$BASE_URL/api/health" | head -n 1 || true
