name: Deploy to Railway (Dockerfile)
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | bash

      - name: Login
        env: { RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} }
        run: railway login --token "$RAILWAY_TOKEN"

      - name: Link (explicit)
        env: { RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} }
        run: |
          railway link --project "${{ vars.RAILWAY_PROJECT_ID }}" \
                       --environment "${{ vars.RAILWAY_ENVIRONMENT_ID }}" \
                       --service "${{ vars.RAILWAY_SERVICE_NAME }}"
          railway whoami
          railway status || true

      - name: Preflight
        run: |
          test -f Dockerfile
          test -f railway.json
          node -v && npm -v

      - name: Deploy
        env: { RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} }
        run: railway up --service "${{ vars.RAILWAY_SERVICE_NAME }}" --yes --verbose --ci

      - name: Post-deploy smoke (non-blocking)
        run: |
          BASE="https://skrblai.io"
          echo "Smoke $BASE"
          curl -Is "$BASE/" | head -n1 || true
          curl -Is "$BASE/api/health" | head -n1 || true